//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week7CodeChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompContactForm
    {
        public int ContactID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailID { get; set; }
        public string phoneNumber { get; set; }
        public string companyName { get; set; }
        public string projdescription { get; set; }
        public string comment { get; set; }
    }
}
